version: '3'

services:
  mongo:
    image: mongo
    container_name: 'mongo'
    networks: 
      - app-network

  mongo_admin:
    image: mongo-express
    container_name: 'mongo_admin'
    environment: 
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8081:8081"
    networks: 
      - app-network

  backend:
    build: ./server/
    container_name: 'backend'
    user: "node"
    depends_on:
      - mongo
    working_dir: /home/node
    environment: 
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ./server/:/home/node
      - /home/node/node_modules
    ports:
      - "3030:3030"
    command: "node index.js"
    networks: 
      - app-network

  frontend:
    build: 
      context: ./
      dockerfile: ./client/Dockerfile-full-build
    container_name: 'frontend'
    depends_on: 
      - backend
    ports:
      - "80:80"
    networks:
      - app-network

networks: 
      app-network:
        driver: bridge
