version: '3'

services:
  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - "27017:27017"
    networks: 
      - app-network

  mongo_admin:
    image: mongo-express
    container_name: 'mongo_admin'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "8081:8081"
    networks: 
      - app-network

  backend:
    image: 127.0.0.1:5000/backend
    build: ./server/
    container_name: 'backend'
    user: "node"
    depends_on:
      - mongo
    working_dir: /home/node
    environment: 
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
    volumes:
      - ~/server/:/home/node
      - /home/node/node_modules
    ports:
      - "3030:3030"
    command: "node index.js"
    networks: 
      - app-network

  frontend:
    image: nginx
    container_name: 'frontend'
    depends_on: 
      - backend
    volumes:
      - ~/nginx/nginx.ini:/etc/nginx/conf.d/default.conf
      - ~/client:/var/www/html   # NOTE: assumes client/build/ directory exists. See README
    ports:
      - "80:80"
    networks:
      - app-network

networks: 
      app-network:
        external:
          name: app-network
